coverage:
  status:
    project:
      default:
        threshold: 20%
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
