coverage:
  status:
    project:
      default: off
      pallets: 
        flags:
          - pallets
    patch: off
    changes: off
        

flags:
  pallets:
    paths:
      - pallets/*/src/lib.rs
